{{- if and (.Values.ingressNginx) (.Values.ingressNginx.enabled) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: {{ .Values.global.namespace | default "argocd" }}
spec:
  project: {{ .Values.global.project | default "default" }}
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.0
    helm:
      values: |
        {{- toYaml .Values.ingressNginx | nindent 8 }}
  destination:
    server: {{ .Values.global.destination.server | default "https://kubernetes.default.svc" }}
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end -}}
