{{- if and (.Values.metricsServer) (.Values.metricsServer.enabled) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: {{ .Values.global.namespace | default "argocd" }}
spec:
  project: {{ .Values.global.project | default "default" }}
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.12.1
    helm:
      values: |
        {{- toYaml (omit .Values.metricsServer "enabled") | nindent 8 }}
  destination:
    server: {{ .Values.global.destination.server | default "https://kubernetes.default.svc" }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end -}}
